console.log("A5.5_HW_1")
console.log("---- ---- ----")
console.log("1.1")
console.log("---- ---- ----")
const favoriteBooks = ["To Kill a Mockingbird", "Pride and Prejudice", "1984", "The Great Gatsby"]; 
console.log(favoriteBooks)
console.log("---- ---- ----")
console.log("1.2")
console.log("---- ---- ----")
console.log(favoriteBooks[1])
console.log("---- ---- ----")
console.log("1.3")
console.log("---- ---- ----")
console.log("nNumber of books :",favoriteBooks.length)
console.log("---- ---- ----")
console.log("1.4")
console.log("---- ---- ----")
console.log(favoriteBooks[favoriteBooks.length -1 ])
console.log("---- ---- ----")
console.log("1.5")
console.log("---- ---- ----")
for(let i = 0;i < favoriteBooks.length;i++)
console.log(favoriteBooks[i])
console.log("---- ---- ----")
console.log("1.6")
console.log("---- ---- ----")
favoriteBooks.push("Harry Potter and the Sorcerer's Stone")
console.log("---- ---- ----")
console.log("1.7")
console.log("---- ---- ----")
console.log(favoriteBooks.length)
console.log(favoriteBooks)